### PR TITLE
MITgcmTools.jl / tutorial_global_oce_biogeo

### PR DESCRIPTION
**Pull request by gaelforget**

### CODE REVIEW

**Comment by gaelforget** [comment]
hoping to do more later today...

**Comment by gaelforget** [comment]
Hi @zhenwu0728 

Does this work for you? 

The tutorial requires fortran compiler to be installed, which is explained in the warning at the top of the notebook, which also gives the link to mybinder which will work via `include("
src/MITgcm_tutorial_global_oce_biogeo.jl")` 

(for now https://mybinder.org/v2/gh/gaelforget/MarineEcosystemsJuliaCon2021.jl/gf1?urlpath=lab is the link that works)  

Would be great to know if you could run the basic workflow locally and / or via mybinder 

(tomorrow I expect to add content in my clone but won't be online)

**Comment by zhenwu0728** [comment]
> Hi @zhenwu0728
> 
> Does this work for you?
> 
> The tutorial requires fortran compiler to be installed, which is explained in the warning at the top of the notebook, which also gives the link to mybinder which will work via `include(" src/MITgcm_tutorial_global_oce_biogeo.jl")`
> 
> (for now https://mybinder.org/v2/gh/gaelforget/MarineEcosystemsJuliaCon2021.jl/gf1?urlpath=lab is the link that works)
> 
> Would be great to know if you could run the basic workflow locally and / or via mybinder
> 
> (tomorrow I expect to add content in my clone but won't be online)

Hi @gaelforget, I'll have a try later today and let you know if it works on my local machine.

**Comment by zhenwu0728** [comment]
> Hi @gaelforget, I'll have a try later today and let you know if it works on my local machine.

I can confirm that your code can run on my local machine.

**Comment by gaelforget** [comment]
Hi @zhenwu0728 

I just uploaded part 2 of the tutorial (`MITgcm_tutorial_global_oce_biogeo_part2.jl`). Running this requires using the _main_ branch (i.e. upcoming release v0.1.23) of https://github.com/gaelforget/MITgcmTools.jl 

Next should be some some plotting, a bit more text in md cells, and then streamlining of the two notebook files...

**Comment by gaelforget** [comment]
just updated, simplified and streamlined as discussed earlier

**Comment by zhenwu0728** [comment]
> just updated, simplified and streamlined as discussed earlier

Just had a quick look. Part 2 also runs successfully on my local machine. But I'm wondering if we need some plots to show the difference between part 1 and part 2 since you change parameters.

**Comment by gaelforget** [comment]
> > just updated, simplified and streamlined as discussed earlier
> 
> Just had a quick look. Part 2 also runs successfully on my local machine. 

Great! We also tried with @briochemc this AM on juliahub, which readily worked.

> But I'm wondering if we need some plots to show the difference between part 1 and part 2 since you change parameters.

Agreed. It's almost done and I expect to upload an update within the hour

**Comment by gaelforget** [comment]
Should be all set. What do you think? 

Ready to merge?

**Comment by zhenwu0728** [comment]
> Should be all set. What do you think?

Yes, looks much better now.

> Ready to merge?

I think it's ready to merge

**Pull request merged**
