### PR TITLE
Add AIBECS example notebook

### PR DESCRIPTION
**Pull request by briochemc**

### CODE REVIEW

**Comment by briochemc** [comment]
ping @gaelforget to test and review the notebook here! It's probably not final but I think it's in good shape now and ready for critics 😄 

If I remember correctly, @gaelforget reviews mine, I'll review @zhenwu0728's, and Wu will review Gael's, right?

**Comment by gaelforget** [comment]
- maybe move "As it travels the oceans ... " ahead of the plot and separate out the last sentence "We call this mean time ..." into separate paragraph
- add run time prediction at the top so user knows how long things should take?

**Comment by gaelforget** [comment]
- it took about 10' for me to get past the `using AIBECS` cell, which I first interpreted as being due to downloads, but then I got an error at the next cell (see below)
- `grd, T = OCIM2.load() ;` initially returned the following error message, which meant that all subsequencent cells also error out. This likely was due my poor internet connection as I am on travel. Calling this code cell again worked and all code cells afterwards worked out as well until `OCEANS = oceanpolygons()` which returned a similar error message
- once I called `OCEANS = oceanpolygons()` a second time then everything else worked out

```
IOError: Could not open stream.
better_readline(::Base.PipeEndpoint)@util.jl:57
better_readline()@util.jl:55
input_choice(::String, ::Char, ::Vararg{Char, N} where N)@util.jl:82
input_bool@util.jl:70[inlined]
check_if_accept_terms(::DataDeps.DataDep{String, String, typeof(AIBECS.OCIM2.fallback_download), typeof(identity)}, ::String, ::String)@resolution_automatic.jl:180
accept_terms@resolution_automatic.jl:163[inlined]
var"#download#13"(::String, ::Nothing, ::Bool, ::typeof(download), ::DataDeps.DataDep{String, String, typeof(AIBECS.OCIM2.fallback_download), typeof(identity)}, ::String)@resolution_automatic.jl:72
download@resolution_automatic.jl:70[inlined]
handle_missing@resolution_automatic.jl:10[inlined]
_resolve(::DataDeps.DataDep{String, String, typeof(AIBECS.OCIM2.fallback_download), typeof(identity)}, ::String)@resolution.jl:83
resolve(::DataDeps.DataDep{String, String, typeof(AIBECS.OCIM2.fallback_download), typeof(identity)}, ::String, ::String)@resolution.jl:29
resolve(::String, ::String, ::String)@resolution.jl:54
resolve@resolution.jl:73[inlined]
var"#load#6"(::String, ::typeof(AIBECS.OCIM2.load))@OCIM2.jl:113
load()@OCIM2.jl:112
top-level scope@Local: 1[inlined]
```

**Comment by gaelforget** [comment]
on the interactive part:

- could be good to have a dedicated cell, say just after the first plot that says 'you can click on a different location on the map and use any of the sliders to change the depth of maps being displayed
- it's a big confusing to have three depth sliders maybe; but maybe not if text upfront is clear
- maybe just before the "Plot it from all angles" / just after the "run the simulation" would be a good place to outline things that user can change / play with / do (change parameters for plotting, look at difference ocean basins, etc)

**Comment by gaelforget** [comment]
Notebook runs throughout without error (with caveat listed above) and is already very well put together, so my sense is that we could merge now & let you address the above comments in subsequent PR? or do you prefer to iterate once more within this PR?

**Comment by briochemc** [comment]
Thank you for the review! These were all very good points. I just realized we can use admonitions in Pluto (with `!!! note "note title"` or `!!! tip "Great tip:"` and so on like in Documenter.jl), so I used that to add plenty of little notes as per your recommendations!

**Comment by briochemc** [comment]
Actually do not merge yet as I am not finished with some polishing!

**Comment by briochemc** [comment]
I think it's good to go now 😄

**Pull request merged**
